import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import { AuthProvider } from "./AuthContext";
import { ThemeProvider } from "next-themes";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add weights you need
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} antialiased`}>
        <AuthProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          </ThemeProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
