version: '3.8'

services:
  # NestJS Backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/chat
      - JWT_SECRET=SECRET_KEY
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # MongoDB Database
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chat
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 