apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  # 🔥 REMOVE THIS:
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: chat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-frontend
                port:
                  number: 3000
